version: '3'

services:
  price-detection-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12002:5000
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai

