version: '3'

services:
  price-detection-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:12002:12002
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
